services:

  # === API Gateway ===
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8083
      - JWT_SECRET=secreto123
    depends_on:
      - auth-service
      - user-service
      - appointment-service
    networks:
      - backend
    restart: always

  # === Auth Service ===
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - auth-db
    networks:
      - backend
    restart: always

  # === Banco de dados do Auth Service ===
  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - backend

  # === User Service ===
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sgh-users-db:5432/sgh-users
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - sgh-users-db
    networks:
      - backend
    restart: always

  # === Banco de dados do User Service ===
  sgh-users-db:
    image: postgres:17
    container_name: sgh-users-db
    restart: always
    environment:
      POSTGRES_DB: sgh-users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - backend

  # === Appointment Service ===
  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://appointment-db:5432/appointments
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - appointment-db
    networks:
      - backend
    restart: always

  # === Banco de dados do Appointment Service ===
  appointment-db:
    image: postgres:17
    container_name: appointment-db
    restart: always
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - appointment_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  auth_data:
  user_data:
  appointment_data:

networks:
  backend:
    driver: bridge
