services:
  postgres:
    image: postgres:15
    container_name: ms-autenticacao-db
    environment:
      POSTGRES_DB: ms_autenticacao
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: SenhaForte@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d ms_autenticacao"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ms-autenticacao-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms_autenticacao
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: SenhaForte@123
    ports:
      - "8081:8081"

volumes:
  postgres_data: